FROM python:3.11-slim

WORKDIR /app

#Install system dependencies
RUN apt-get update && apt-get install -y build-essential

#Copy requirements first (better caching)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

#Copy project
COPY . .

#Expose FastAPI port
EXPOSE 8000

#Default command
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]